---
title: "Singapore_ExclusivePooledAMoD_SEM"
author: "Rachel Luo"
date: "10/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Dropbox (MIT)/MobilitySurveyExpansion/Singapore/Data/Data_Exploration/Scripts+Data/")
```

```{r cars, echo = FALSE}
library(dplyr)
library(car) 
library(ggplot2)
library(stargazer)
library(MASS)
library(forecast) 
library(stats)
library(moments)
library(lavaan)
library(lavaanPlot)

rm(list = ls()) 
```

```{r datasets, echo=FALSE}
# read in data, delete headers, and make working copy of data
Data_raw <- read.csv("latentdata_withfactorscore.csv", stringsAsFactors=FALSE)
Data_raw <- Data_raw[3:nrow(Data_raw),]
Data <- Data_raw
```

```{r recoding data}
### Cleaning demographic data
# # income coding
# 1 = "Household currently has no source of earned income"
# 2 = "Below S$ 1,000"
# 3 = "S$ 1,000-2,499"
# 4 = "S$ 2,500-3,999"
# 5 doesn't exist
# 6 = "S$ 4,000-4,999"
# 7 = "S$ 5,000-5,999"
# 8 = "S$ 6,000-6,999"
# 9 = "S$ 7,000-7,999"
# 10 = "S$ 8,000-8,999"
# 11 = "S$ 9,000-9,999"
# 12 = "S$ 10,000-10,999"
# 13 = "S$ 11,000-12,999"
# [14 doesn't exist]
# 15 = "S$ 13,000-14,999"
# [16 doesn't exist in the data]
# 17 = "S$15,000-17,499"
# 18 = "$17,500-19,999"
# 19 = "S$20,000 or more"
# And there may be some missingness, which should be NA

Data <- Data %>% mutate(DOB = as.numeric(as.character(age)),
                        Age = 2019 - DOB,
                        Male = ifelse(gender==1, 1, 0),
                        ColDeg = ifelse(educ==5, 1, 0),
                        GradDeg = ifelse(educ==6 | educ==7, 1, 0),
                        Secondary = ifelse(educ==2, 1, 0),
                        PostSecondary = ifelse(educ==3, 1, 0),
                        Diploma = ifelse(educ==4, 1, 0),
                        University = ifelse(educ %in% 5:7, 1, 0),
                        Unemployed = ifelse(employ==6 | employ==7, 1, 0), 
                        FullEmploy = ifelse(employ==1 | employ ==3, 1, 0), #1-full time employed, 3-full time self employed
                        Student = ifelse(employ==9, 1, 0),
                        Kids = ifelse(kids>1, 1, 0),
                        OwnsCar = ifelse(hhcars==1, 0, 1),
                        Age1 = ifelse(Age<30, 1, 0),
                        Age2 = ifelse(Age %in% 30:44, 1, 0),
                        Age3 = ifelse(Age %in% 45:54, 1, 0),
                        Age4 = ifelse(Age %in% 55:64, 1, 0),
                        Age5 = ifelse(Age>64, 1, 0),
                        Own_house = ifelse(ownrent == 1 | ownrent == 2, 1, 0),
                        HHIncLow = ifelse(hhinc == 1 | hhinc == 2 | hhinc == 19, 1, 0),
                        HHIncMid = ifelse(hhinc == 3 | hhinc == 4 | hhinc == 5, 1, 0),
                        Inc1 = ifelse(hhinc %in% 1:3, 1, 0), # <S$2,500, 11.5% of sample
                        Inc2 = ifelse(hhinc %in% 4:7, 1, 0), #S$2,500-5,999, 24.8% of sample
                        Inc3 = ifelse(hhinc %in% 8:11, 1, 0), #S$6,000-9,999, 26.4% of sample
                        Inc4 = ifelse(hhinc %in% 12:15, 1, 0), #S$10,000-14,999, 21.6% of sample
                        Inc5 = ifelse(hhinc %in% 17:19, 1, 0), #S$15,000+, 15.8% of sample
                        license_holder = ifelse(license == 1, 0, 1), #Yes, if person holds any type of license
                        AV_Safe = ifelse(av_safeperc == 1 | av_safeperc == 2, 1, 0) #Includes safe, somewhat safe
                        
)

#reverse the Likert scales used for exclusive, pooled AMoD to ease interpretability in regressions
Data$ESAV_Likert_rev <- as.numeric(as.character(car::recode(Data$sav_intenduse_1, "1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1")))
Data$PSAV_Likert_rev <- car::recode(Data$sav_intenduse_2, "1=7; 2=6; 3=5; 4=4; 5=3; 6=2; 7=1")

# create list of attitudinal factors
factor_scores <- c("hedonic_factorscore",	"trust_factorscore", "cp_use_factorscore",
                   "cp_own_factorscore", "busshame_factorscore.bus_shame1",	"busshame_factorscore.bus_shame2",
                   "perfor_factorscore", "efexp_factorscore",	"socinf_factorscore",
                   "faccond_factorscore",	"techinst_factorscore",	"genprd_factorscore",	"matera_factorscore")

#HHCars: How many cars does your household currently lease or own?
#1 = "0 car", 2 = "1 car", 3 = "2 cars", 4 = "3 or more cars"
Data$HHCars <- car::recode(Data$hhcars, "1=0; 2=1; 3=2; 4=3")

# Data on number of exclusive, pooled ridehailing trips currently taken per month
Data <- Data %>% mutate(prh_trips_10 = ifelse(is.na(prh_trips_10), 0, prh_trips_10),
                        srh_trips_2 = ifelse(is.na(srh_trips_2), 0, srh_trips_2))

#Clean the Q8 question group: turn all current travel modes and ridesharing trip counts data into numeric variables from factors
Q8_trips <- c("q8_1", "q8_2", "q8_3", "q8_4", "q8_5", "q8_6", "q8_7", "q8_8", "q8_9", "prh_trips_10","srh_trips_2")
Data[Q8_trips] <- sapply(Data[Q8_trips], as.character)
Data[Q8_trips] <- sapply(Data[Q8_trips], as.numeric)
sapply(Data[Q8_trips], class)

Data$q8_PTShare = Data$q8_6 + Data$q8_7
summary(Data$q8_PTShare)

Data$q8_nonmotorShare = Data$q8_8 + Data$q8_9
summary(Data$q8_nonmotorShare)

Data <- Data %>% mutate(Nonmotor_superuser = ifelse(q8_nonmotorShare >= 20, 1, 0), #110 individuals
                        Nonmotor_frequser = ifelse(q8_nonmotorShare %in% 10:19, 1, 0), #242 individuals
                        Nonmotor_reguser = ifelse(q8_nonmotorShare %in% 1:9, 1, 0), #214 individuals
                        Nonmotor_nonuser = ifelse(q8_nonmotorShare < 1, 1, 0), #234 individuals
                        PT_superuser = ifelse(q8_PTShare >= 71, 1, 0),  #188 individuals
                        PT_frequser = ifelse(q8_PTShare %in% 46:70, 1, 0), #205 individuals
                        PT_reguser = ifelse(q8_PTShare %in% 11:45, 1, 0), #231 individuals
                        PT_lowuser = ifelse(q8_PTShare<11, 1, 0), #176 individuals; cutoff based on summary/hist; only 71 individuals are non-users, as Singapore is super transit-oriented
                        Taxi_frequser = ifelse(q8_2 >= 8, 1, 0), # 189 individuals
                        Taxi_reguser = ifelse(q8_2 %in% 1:7, 1, 0), #185 individuals
                        Taxi_nonuser = ifelse(q8_2 < 1, 1, 0), #426 individuals
                        Car_superuser = ifelse(q8_1 >= 60, 1, 0),  #175 individuals
                        Car_frequser = ifelse(q8_1 %in% 20:59, 1, 0), #192 individuals
                        Car_reguser = ifelse(q8_1 %in% 1:19, 1, 0), #147 individuals
                        Car_nonuser = ifelse(q8_1<1, 1, 0), #286 individuals
                        ERH_frequser = ifelse(q8_3 >= 10, 1, 0), #282 individuals
                        ERH_reguser = ifelse(q8_3 %in% 1:9, 1, 0), #225 individuals, Q1-Q3
                        ERH_nonuser = ifelse(q8_3 < 1, 1, 0), #293 individuals
                        PRH_frequser = ifelse(q8_4 >= 9, 1, 0), #119 individuals
                        PRH_reguser = ifelse(q8_4 %in% 1:8, 1, 0), #108 individuals
                        PRH_nonuser = ifelse(q8_4 < 1, 1, 0) #573 individuals
                        )

```

```{r SEM}
# final simultaneous estimation of SEM and CFA

model_FINAL <- '
                      perfor_exp =~ 1*perfexp_1_adj + perfexp_2_adj + perfexp_3_adj + perfexp_4_adj + perfexp_5_adj + perfexp_7_adj 
                      effo_exp =~ 1*effexp_1_adj + effexp_2_adj + effexp_3_adj + effexp_6_adj
                      soca_inf =~ 1*socinf_1_adj + socinf_2_adj + socinf_3_adj
                      fac_cond =~ 1*faccond_2_adj + faccond_3_adj + faccond_4_adj
                      hedo_motv =~ 1*hedmotiv_1_adj + hedmotiv_2_adj + hedmotiv_4_adj
                      trust =~ 1*trust_1_adj + trust_2_adj + trust_3_adj + trust_4_adj + trust_5_adj + trust_7_adj
                      trust_2_adj ~~ trust_5_adj
                      tech_int =~ 1*techint_1_adj + techint_4_adj + techint_5_adj + techint_7_adj + techint_8_adj
                      techint_7_adj   ~~  techint_8_adj     
                      
                      ESAV_Likert_rev ~ Inc1 + Inc2 + Inc4 + Inc5 + Age + Male + University + FullEmploy + Kids + OwnsCar +
                      AV_Safe +  av_know +
                      perfor_exp + effo_exp + soca_inf + fac_cond + hedo_motv + trust + tech_int + 
                      prh_trips_10 + srh_trips_2 + Nonmotor_superuser + Nonmotor_frequser + Nonmotor_reguser +
                      PT_superuser + PT_frequser + PT_reguser + 
                      Car_superuser + Car_frequser + Car_reguser + Taxi_frequser + Taxi_reguser
                      
                      PSAV_Likert_rev ~ Inc1 + Inc2 + Inc4 + Inc5 + Age + Male + University + FullEmploy + Kids + OwnsCar +
                      AV_Safe + av_know +
                      perfor_exp + effo_exp + soca_inf + fac_cond + hedo_motv + trust + tech_int + 
                      prh_trips_10 + srh_trips_2  + Nonmotor_superuser + Nonmotor_frequser + Nonmotor_reguser +
                      PT_superuser + PT_frequser + PT_reguser + 
                      Car_superuser + Car_frequser + Car_reguser + Taxi_frequser + Taxi_reguser
                      
                      ESAV_Likert_rev ~~ PSAV_Likert_rev
                    '    

model_FINAL_fit <- lavaan::sem(model_FINAL, data = Data)
lavaan::summary(model_FINAL_fit, standardized = TRUE, fit.measures = TRUE)
lavaan::inspect(model_FINAL_fit, 'r2') #ESAV 0.448; PSAV = 0.441

```

```{r plots}
# Plotting respondents' intention to use exclusive AMoD
ggplot(Data, aes(x = ESAV_Likert_rev)) +
  geom_histogram(binwidth = 1, fill = "#61f2f5", col = "white", aes(y = 100*(..count..)/sum(..count..))) + 
  xlab("Likert Scale, 1 = Extremely unlikely, 7 = Extremely likely") + theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = seq(0,7,1), lim = c(0.5,7.5)) + ylab("Percent of all respondents (%)")

# Plotting respondents' intention to use pooled AMoD
ggplot(Data, aes(x = PSAV_Likert_rev)) +
  geom_histogram(binwidth = 1, fill = "#5edfff", col = "white", aes(y = 100*(..count..)/sum(..count..))) + 
  xlab("Likert Scale, 1 = Extremely unlikely, 7 = Extremely likely") + theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = seq(0,7,1), lim = c(0.5,7.5)) + ylab("Percent of all respondents (%)")


```

